<a href="https://colab.research.google.com/github/ephantus9/ephantuswa/blob/main/Copy_of_Ephantus_Homework_2_NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework Assignment
**Name:** EPHANTUS WANDUA

Complete all tasks and ensure that you thoroughly test your code. Submit your completed notebook as a PDF, including outputs for all cells.

**Instructions:**
1. Complete all tasks outlined in this notebook.
2. Include validation functions wherever applicable to ensure the correctness of your solutions.
3. Thoroughly test your code to handle various scenarios, including edge cases.
4. Verify that the notebook is complete:
 - Run all cells to ensure all outputs are generated and up-to-date.
 - Review your notebook for clarity and ensure no unnecessary or incomplete outputs remain.
5. Save the notebook as a PDF:
 - Click on **File** in the top-left menu.
 - Select **Print** and save the notebook as a PDF.
6. Submit the generated PDF file in **Brightspace**.

# Part A: Shape & Memory Reasoning (25%)

Without running, answer:

In [15]:
import numpy as np

a = np.arange(12)
b = a.reshape((3, 4))
c = b[:, ::2]
print(c.shape)


(3, 2)


**Question A.1:** What is the shape of c?

(3,2)

**Question A.2:** Is c a view or a copy? Why?

c is a view not a copy.
This is because its created by basic slicing and shares memory with b and thus if i modify an element in c, the corresponding element in b changes as well

**Question A.3:** If c[0,0] = 999, does a change? Explain.

Yes, a does change. This is because c is a view and the assignment modifies the shared underlying data rather than a separate copy.

# Part B: Vectorized Rewrite (Core Skill) (25%)

Given:

In [16]:
def slow_norm(x):
    total = 0
    for v in x:
        total += v * v
    return total ** 0.5


**Task B.1:** Rewrite using NumPy (no loops)

In [17]:
# Your solution here
import numpy as np
def fast_norm (x):
  return np.sqrt(np.dot(x,x))

**Task B.2:** Verify both versions give the same result

In [18]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])
s = slow_norm(x)
f = fast_norm(x)
print (f'This the result slow_norm: {s} \nThis the result fast_norm: {f}')

This the result slow_norm: 11.832159566199232 
This the result fast_norm: 11.832159566199232


**Task B.3:** State one reason NumPy is faster (conceptual)

NumPy is faster because it executes operations in compiled C code on whole arrays at once, avoiding slow Python-level loops

# Part C: Silent Bug Detection (20%)

In [19]:
x = [[1, 2], [3, 4], [5, 6]]
y = x.copy()

y[0][0] = 99
x

[[99, 2], [3, 4], [5, 6]]

**Question C.1:** What is the value of x after this code runs?

[[99, 2], [3, 4], [5, 6]]

**Question C.2:** Why does modifying y change x, even though y is a “copy”?

This is because x.copy() is a shallow copy and therefore modifying y changes x since they share the inner list between x and y

**Question C.3:** Show two different correct ways to prevent this bug.

In [20]:
# Your solution:
import copy

x = [[1, 2], [3, 4], [5, 6]]
y = copy.deepcopy(x)

y[0][0] = 99
x

[[1, 2], [3, 4], [5, 6]]

In [21]:
x = [[1, 2], [3, 4], [5, 6]]
y = [row.copy() for row in x]

y[0][0] = 99
x

[[1, 2], [3, 4], [5, 6]]

**Question C.4:** For each fix, state whether the inner lists share memory with x.

using deepcopy, The inner list do not share memory with x.  
using the ro.copy, the inner list do not share memory with x

# Part D: Small Real-World Task (20%)

Given:

In [22]:
data = np.array([
    [72, 85, 90],
    [88, 79, 93],
    [91, 92, 87]
])

Each row = student, each column = exam.

**Task D.1:** Compute each student’s average

In [23]:
# Your code
Student_averages = np.mean (data, axis=1)
print(Student_averages)

[82.33333333 86.66666667 90.        ]


**Task D.2:** Normalize scores column-wise to mean 0, std 1

In [24]:
# Your code
col_mean = np.mean(data, axis = 0)
col_std = np.std (data, axis = 0)
normalized = (data - col_mean)/col_std
print(normalized)

[[-1.39888134 -0.06274558  0.        ]
 [ 0.5195845  -1.19216603  1.22474487]
 [ 0.87929684  1.25491161 -1.22474487]]


In [25]:
np.mean(normalized, axis=0)
# i have manually confirmed the mean to ensure its zero

array([-5.55111512e-16,  8.14163551e-16,  0.00000000e+00])

In [26]:
np.std(normalized, axis=0)
# i have manually computed std to confirm its 1

array([1., 1., 1.])

**Task D.3:** Identify which exam had highest variance

In [27]:
# Your code
variances = np.var(data, axis = 0)
variances

array([69.55555556, 28.22222222,  6.        ])

Exam 1 has the highest variances, even checking on the normlaized valaues, the absolute value in exam 1 is the highest

# Part E: GPT Reflection (10%)

**Question E.1:** How GPT helped

yes

**Question E.1:** One mistake or limitation

GPT can sometimes give correct code without explicitly warning about edge cases.eg, when a column has zero variance during normalization

**Question E.1:** One thing you verified manually

I manually checked that each normalized column actually has mean 0 and standard deviation 1 by recomputing the statistics after normalization.